model:
  n_hidden: 512
  n_layer: 2

training:
  lr: 1e-2
  weight_decay: 5e-5
  n_epochs: 200
  patience: ~
  criterion: ~

dataset:
  feat_norm: false
  sparse: true

analysis:
  flag: false
  project: gsl
  save_graph: false

search:
  par: false