model:
  n_hidden: 1024
  n_layer: 2

training:
  lr: 1e-3
  weight_decay: 0
  n_epochs: 200
  patience: ~
  criterion: ~

dataset:
  feat_norm: false
  sparse: true

analysis:
  flag: false
  project: gsl
  save_graph: false