model:
  n_hidden: 256
  n_layer: 2

training:
  lr: 1e-3
  weight_decay: 5e-5
  n_epochs: 200
  patience: ~
  criterion: ~

dataset:
  feat_norm: true
  sparse: true

analysis:
  flag: false
  project: gsl
  save_graph: false