model:
  n_hidden: 128
  n_layer: 2

training:
  lr: 0.1
  weight_decay: 5e-4
  n_epochs: 200
  patience: ~
  criterion: ~

dataset:
  feat_norm: true
  sparse: true

analysis:
  flag: false
  project: gsl
  save_graph: false